### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by almaan**
Hello Dylan,

it seems like the `cell_type_names` argument isn't passed to `process_cell_type_info`, at least it kept throwing an error until added, then everything worked smoothly.

Best
Alma

### CODE REVIEW

**Comment by asifzubair** [comment]
Hi @almaan !

I assume you are running Visium data. I think there is an innocuous bug in `read.VisiumSpatialRNA` as well. 

Wondering if you too ran into it? 

Also, thanks for putting in this PR ... think a lot of folks are running into this bug.

Asif

**Review by dmcable — APPROVED** [review]
Looks great! Thanks for the fix, Alma!

**Comment by dmcable** [comment]
For your second change of `MIN_UMI = 0` in choose_sigma_c, I'm going to update this to be a changeable parameter, with default value 300.

**Comment by dmcable** [comment]
> Hi @almaan !
> 
> I assume you are running Visium data. I think there is an innocuous bug in `read.VisiumSpatialRNA` as well.
> 
> Wondering if you too ran into it?
> 
> Also, thanks for putting in this PR ... think a lot of folks are running into this bug.
> 
> Asif

Hi Asif, what is the issue you have encountered with the `read.VisiumSpatialRNA`?

**Comment by almaan** [comment]
> Hi @almaan !
> 
> I assume you are running Visium data. I think there is an innocuous bug in `read.VisiumSpatialRNA` as well.
> 
> Wondering if you too ran into it?
> 
> Also, thanks for putting in this PR ... think a lot of folks are running into this bug.
> 
> Asif

Hi Asif,

actually, this was not run on Visium data but rather on a synthetic data set. We have incorporated RCTD as one of the methods to be benchmarked in the SCOP (Single Cell Open Problems) task of spatial decomposition, see [LINK1](https://github.com/singlecellopenproblems/SingleCellOpenProblems) and [LINK2](https://github.com/singlecellopenproblems/SingleCellOpenProblems/pull/309). So I have not yet experienced any problems with `read.VisiumSpatialRNA`.

**Comment by almaan** [comment]
> For your second change of `MIN_UMI = 0` in choose_sigma_c, I'm going to update this to be a changeable parameter, with default value 300, the logic being to exclude smaller pixels in order to focus on more informative pixels.

Awesome, thank you!

**Comment by asifzubair** [comment]
Hi @dmcable , 

When using the `read.VisiumSpaialRNA` function, I was getting the following error:

```
Error in check_coords(coords) : 
  SpatialRNA: the second dimension of coords is not 2. Please enforce that dim(coords)[2] == 2 (x and y coordinates).
```

I fixed it by choosing only the `x` and `y` columns when reading `spatial/tissue_positions_list.csv` from the SpaceRanger folder.

**Comment by asifzubair** [comment]
Hi @almaan , thank you for the links ... looks interesting!

**Comment by dmcable** [comment]
> Hi @dmcable ,
> 
> When using the `read.VisiumSpaialRNA` function, I was getting the following error:
> 
> ```
> Error in check_coords(coords) : 
>   SpatialRNA: the second dimension of coords is not 2. Please enforce that dim(coords)[2] == 2 (x and y coordinates).
> ```
> 
> I fixed it by choosing only the `x` and `y` columns when reading `spatial/tissue_positions_list.csv` from the SpaceRanger folder.

Thanks for letting me know @asifzubair -- if possible would you please be able to send me the Visium files (full or subsampled) so that I can see the format of the Visium data and fix this issue in that function? Thank you.

**Comment by asifzubair** [comment]
Firstly, sorry @almaan , for hijacking your PR. @dmcable , please let me know if you want me to make a separate issue. =)

For the test data, I am simply using one of the datasets from 10X, for example - https://support.10xgenomics.com/spatial-gene-expression/datasets/1.1.0/V1_Human_Heart

**Comment by dmcable** [comment]
@asifzubair this issue should be fixed now. If the issue persists, please create a new issue. Thank you!

**Pull request merged**
